### ISSUE TITLE
re2.search/match return 1; pattern methods return None

### ISSUE THREAD

**Issue by abarnert** [axiak/pyre2#14]
>>> x=29; r, s = 'a?'*x+'a'*x, 'a'*x
>>> re2.match(r, s)
1
>>> re2.search(r, s)
1
>>> re2.compile(r).search(s)
>>> re2.compile(r).match(s)

By comparison:
>>> re.match(r, s)
<_sre.SRE_Match at 0x104cfc100>

… and likewise for the other three (to save you the 4 minutes or so to test for yourself:)).

**Comment by axiak** [comment]
Published a fix to pypi
