### ISSUE TITLE
import re2 in Python in Mac OS X

### ISSUE THREAD

**Issue by RahulKulhari** [axiak/pyre2#29]
>>> import re2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/us/Anaconda/anaconda/lib/python2.7/site-packages/re2.so, 2): Symbol not found: __ZN3re23RE213GlobalReplaceEPSsRKS0_RKNS_11StringPieceE
  Referenced from: /Users/us/Anaconda/anaconda/lib/python2.7/site-packages/re2.so
  Expected in: dynamic lookup

Installation Procedure i followed:

first i install re2 using

>brew install re2

then i did:

$ git clone git://github.com/axiak/pyre2.git
$ cd pyre2.git
$ sudo python setup.py install

I am getting this error when i am importing re2 in python Mac OS X.

How to solve this issue ?

**Comment by Tafkas** [comment]
I face the same issue.

**Comment by kmike** [comment]
It looks like Anaconda issue - it doesn't play well with python C extensions installed using setuptools/distutils.

**Comment by Tafkas** [comment]
In my case I am not using Anaconda but regular python installed by homebrew. re2 was also installed by homebrew.

**Comment by kmike** [comment]
Hmm, I've just tried the following, it worked:

```
brew upgrade re2
mkvirtualenv tst
pip install https://github.com/axiak/pyre2/archive/master.zip#egg=pyre2 
```

**Comment by axiak** [comment]
I can't reproduce this on OS X
