### ISSUE TITLE
Update PyPi

### ISSUE THREAD

**Issue by gruns** [axiak/pyre2#42]
Please update PyPi.

Important fixes like https://github.com/axiak/pyre2/commit/89e0b255b793f57ab0a146c7f7b6f442ac019598 aren't included in v0.2.22, which was uploaded over a year ago, on 2015-05-15.

**Comment by ghost** [comment]
+1

Please :) <3

**Comment by messense** [comment]
+1

**Comment by luoqishuai** [comment]
+1

**Comment by axiak** [comment]
I think this is done.. can you check it for me?

**Comment by gruns** [comment]
> I think this is done.. can you check it for me?

Confirmed.

If curious, you can confirm this personally, too, by downloading the latest
version of re2, v0.2.24, from PyPi directly

 *  https://files.pythonhosted.org/packages/14/b0/e3476ed13e60fc7fb0d172926809c53be7a8d02f14191ada449a6d572dcb/re2-0.2.24.tar.gz

unpacking, and inspecting setup.py therein. v0.2.24's setup.py includes the

```
extra_compile_args=['-std=c++11'],
```

addition from 89e0b25.


Thank you for updating re2 on PyPi, Michael.
